StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{68E30B9C9705C951}" {
   Id "AR-PODVAL-Author_Podval"
   Target_en_us "Podval"
   Target_ru_ru "Подвал"
   Status TRANSLATION_PENDING
   Modified 1759710191
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E0A45883867562}" {
   Id "AR-PODVAL-Author_Vlad333000"
   Target_en_us "Podval & Vlad333000"
   Target_ru_ru "Подвал & Vlad333000"
   Status TRANSLATION_PENDING
   Modified 1759553702
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E0A458F8A31E3C}" {
   Id "AR-PODVAL-CAH-Scenario_Description_Beauregard_RHS"
   Target_en_us "Following the sudden escalation of the conflict on Arland Island, the strategic town of Beauregard found itself on the front line. Control of its intersections, storage areas, and port infrastructure will allow one side to gain a foothold in the region and secure supplies for its forces. Russian Forces and US Army units are striving to take key positions in the town and hold them at all costs."
   Target_ru_ru "После внезапного обострения конфликта на острове Арланд стратегический город Борегар оказался на линии фронта. Контроль над его перекрёстками, складскими зонами и портовой инфраструктурой позволит одной из сторон закрепиться в регионе и обеспечить снабжение своих сил. Подразделения ВС РФ и Армии США стремятся занять ключевые позиции в городе и удержать их любой ценой."\
   ""
   Status TRANSLATION_PENDING
   Modified 1759553605
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E894BC9CF66079}" {
   Id "AR-PODVAL-CAH-Scenario_Description_Briars_Coast_RHS"
   Target_en_us "Following the Russian air strike on Morton, a U.S. fuel depot southeast of Manatee was left undefended. Its capture could disrupt plans to evacuate U.S. Army forces from the island."
   Target_ru_ru "После удара ВС РФ по Мортону американский склад ГСМ к юго-востоку от Ламантина остался без прикрытия. Его захват может сорвать планы эвакуации сил Армии США с острова."
   Status TRANSLATION_PENDING
   Modified 1760076516
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E8A5CA2482D206}" {
   Id "AR-PODVAL-CAH-Scenario_Description_Castle_RHS"
   Target_en_us "A small number of US troops are fighting for their lives. Cut off by the Russian forces at Pennants Pass and retreating from Saint-Pierre, they now have no choice but to secure the Montfort Castle. From this ancient stronghold they may be able to hold out, but just a little longer..."
   Target_ru_ru "Немногочисленным американским подразделениям, отрезанным силами ВС РФ на перевале Пеннант и отходящим от Сент-Пьерра, приходится теперь держать оборону в замке Монфор. Возможно, им удастся продержаться в этой древней крепости, но совсем недолго..."
   Status TRANSLATION_PENDING
   Modified 1760079411
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E8A5CEAA46A689}" {
   Id "AR-PODVAL-CAH-Scenario_Description_Concrete_Plant_RHS"
   Target_en_us "The Arma-Beton concrete plant is a key defensive position on the road to Everon International. If Russian forces take it, they can stage an attack on the airport and surround US troops in Saint-Philippe!"
   Target_ru_ru "Бетонный завод \"Arma-Beton\" — ключевая оборонительная позиция по дороге в международный аэропорт Эверона. Если российские войска захватят его, они смогут организовать атаку на аэропорт и окружить американские войска в Сент-Филиппе!"
   Status TRANSLATION_PENDING
   Modified 1760080970
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E8A5C32B20555C}" {
   Id "AR-PODVAL-CAH-Scenario_Description_Factory_RHS"
   Target_en_us "Saint-Philippe hangs in the balance. Fierce fighting around the furniture factory on the outskirts of the town has forced both sides from the site. But such an impasse cannot last — whoever captures and reinforces this position will most likely take the capital, and Everon itself."
   Target_ru_ru "Сент-Филипп висит на волоске. Ожесточенные бои вокруг мебельной фабрики на окраине города вынудили обе стороны покинуть это место. Но такое положение дел не может длиться вечно — тот, кто захватит и укрепит эту позицию, скорее всего, захватит и столицу, и Эверон в целом."
   Status TRANSLATION_PENDING
   Modified 1760082604
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E0A2A8E436F154}" {
   Id "AR-PODVAL-CAH-Scenario_Name_Beauregard_RHS"
   Target_en_us "Capture & Hold - Beauregard RHS"
   Target_ru_ru "Capture & Hold - Борегар RHS"
   Status TRANSLATION_PENDING
   Modified 1759552851
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E2D43A9912A61A}" {
   Id "AR-PODVAL-CAH-Scenario_Name_Beauregard_RHS_Inf"
   Target_en_us "Capture & Hold - Beauregard RHS Infantry"
   Target_ru_ru "Capture & Hold - Борегар RHS Пехотный"
   Status TRANSLATION_PENDING
   Modified 1759696968
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E894BD04CB762E}" {
   Id "AR-PODVAL-CAH-Scenario_Name_Briars_Coast_RHS"
   Target_en_us "Capture & Hold - Briars Coast RHS"
   Target_ru_ru "Capture & Hold - Дикие Поля RHS"
   Status TRANSLATION_PENDING
   Modified 1760076707
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E894BC78FD0C1D}" {
   Id "AR-PODVAL-CAH-Scenario_Name_Briars_Coast_RHS_Inf"
   Target_en_us "Capture & Hold - Briars Coast RHS Infantry"
   Target_ru_ru "Capture & Hold - Дикие Поля RHS Пехотный"
   Status TRANSLATION_PENDING
   Modified 1760076751
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E8A5CA3EFBDA16}" {
   Id "AR-PODVAL-CAH-Scenario_Name_Castle_RHS"
   Target_en_us "Capture & Hold - Montfort Castle RHS"
   Target_ru_ru "Capture & Hold - Замок Монфорт RHS"
   Status TRANSLATION_PENDING
   Modified 1760079371
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E8A5CA20A7BF70}" {
   Id "AR-PODVAL-CAH-Scenario_Name_Castle_RHS_Inf"
   Target_en_us "Capture & Hold - Montfort Castle RHS Infantry"
   Target_ru_ru "Capture & Hold - Замок Монфорт RHS Пехотный"
   Status TRANSLATION_PENDING
   Modified 1760079369
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E8A5CEAE0B375E}" {
   Id "AR-PODVAL-CAH-Scenario_Name_Concrete_Plant_RHS"
   Target_en_us "Capture & Hold - Concrete Plant RHS"
   Target_ru_ru "Capture & Hold — Бетонный завод RHS"
   Status TRANSLATION_PENDING
   Modified 1760080970
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E8A5CE90051BEB}" {
   Id "AR-PODVAL-CAH-Scenario_Name_Concrete_Plant_RHS_Inf"
   Target_en_us "Capture & Hold - Concrete Plant RHS Infantry"
   Target_ru_ru "Capture & Hold — Бетонный завод RHS Пехотный"
   Status TRANSLATION_PENDING
   Modified 1760080970
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E8A5C324DE7C49}" {
   Id "AR-PODVAL-CAH-Scenario_Name_Factory_RHS"
   Target_en_us "Capture & Hold - Almara Factory RHS"
   Target_ru_ru "Capture & Hold — Завод Almara RHS"
   Status TRANSLATION_PENDING
   Modified 1760082609
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E8A5C326FAD3FD}" {
   Id "AR-PODVAL-CAH-Scenario_Name_Factory_RHS_Inf"
   Target_en_us "Capture & Hold - Almara Factory RHS Infantry"
   Target_ru_ru "Capture & Hold — Завод Almara RHS Infantry"
   Status TRANSLATION_PENDING
   Modified 1760082611
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E0A45DCDA2278B}" {
   Id "AR-PODVAL-MapLocation_Beauregard_NorthRoad"
   Target_en_us "Road to Beauregard (North)"
   Target_ru_ru "Дорога на Борегар (Север)"
   Status TRANSLATION_PENDING
   Modified 1759560408
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E0A4567BFE41BC}" {
   Id "AR-PODVAL-MapLocation_Beauregard_SouthRoad"
   Target_en_us "Road to Beauregard (South)"
   Target_ru_ru "Дорога на Борегар (Юг)"
   Status TRANSLATION_PENDING
   Modified 1759560400
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E0A45D22D70A87}" {
   Id "AR-PODVAL-MapLocation_WickPoint_Lighthouse"
   Target_en_us "Lighthouse at Wick Point"
   Target_ru_ru "Маяк на Страшном мысе"
   Status TRANSLATION_PENDING
   Modified 1760076756
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
 }
}