StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{68E30B9C9705C951}" {
   Id "AR-PODVAL-Author_Podval"
   Target_en_us "Podval"
   Target_ru_ru "Подвал"
   Status TRANSLATION_PENDING
   Modified 1759710191
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E0A45883867562}" {
   Id "AR-PODVAL-Author_Vlad333000"
   Target_en_us "Podval & Vlad333000"
   Target_ru_ru "Подвал & Vlad333000"
   Status TRANSLATION_PENDING
   Modified 1759553702
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E0A458F8A31E3C}" {
   Id "AR-PODVAL-CAH-Scenario_Description_Beauregard_RHS"
   Target_en_us "Following the sudden escalation of the conflict on Arland Island, the strategic town of Beauregard found itself on the front line. Control of its intersections, storage areas, and port infrastructure will allow one side to gain a foothold in the region and secure supplies for its forces. Russian Forces and US Army units are striving to take key positions in the town and hold them at all costs."
   Target_ru_ru "После внезапного обострения конфликта на острове Арланд стратегический город Борегар оказался на линии фронта. Контроль над его перекрёстками, складскими зонами и портовой инфраструктурой позволит одной из сторон закрепиться в регионе и обеспечить снабжение своих сил. Подразделения ВС РФ и Армии США стремятся занять ключевые позиции в городе и удержать их любой ценой."\
   ""
   Status TRANSLATION_PENDING
   Modified 1759553605
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E0A2A8E436F154}" {
   Id "AR-PODVAL-CAH-Scenario_Name_Beauregard_RHS"
   Target_en_us "Capture & Hold - Beauregard RHS"
   Target_ru_ru "Capture & Hold - Борегар RHS"
   Status TRANSLATION_PENDING
   Modified 1759552851
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E2D43A9912A61A}" {
   Id "AR-PODVAL-CAH-Scenario_Name_Beauregard_RHS_Inf"
   Target_en_us "Capture & Hold - Beauregard RHS Infantry"
   Target_ru_ru "Capture & Hold - Борегар RHS Пехотный"
   Status TRANSLATION_PENDING
   Modified 1759696968
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E0A45DCDA2278B}" {
   Id "AR-PODVAL-MapLocation_Beauregard_NorthRoad"
   Target_en_us "Road to Beauregard (North)"
   Target_ru_ru "Дорога на Борегар (Север)"
   Status TRANSLATION_PENDING
   Modified 1759560408
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E0A4567BFE41BC}" {
   Id "AR-PODVAL-MapLocation_Beauregard_SouthRoad"
   Target_en_us "Road to Beauregard (South)"
   Target_ru_ru "Дорога на Борегар (Юг)"
   Status TRANSLATION_PENDING
   Modified 1759560400
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{68E0A45D22D70A87}" {
   Id "AR-PODVAL-MapLocation_WickPoint_Lighthouse"
   Target_en_us "Lighthouse at Wick Point"
   Target_ru_ru "Маяк на Страшном мысе"
   Modified 1759554792
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
 }
}