SCR_FactionPlayerLoadout : "{62306181A86F2553}Configs/Loadouts/USAF/USMC/MEF/Loadout_USAF_Base.conf" {
 m_sLoadoutName "#AR-Role_Rifleman"
 m_sLoadoutResource "{3AB4CA3D88DB69FA}Prefabs/Characters/Factions/BLUFOR/RHS_USAF/RHS_USAF_USMC_MEF/Character_Podval_USMC_Rifleman.et"
 m_sLoadoutImage "{344FE3D1529D1192}UI/Textures/EditorPreviews/Characters/Factions/BLUFOR/RHS_USAF/RHS_USAF_USMC_MEF/Character_RHS_USAF_USMC_Rifleman.edds"
}