SCR_FactionPlayerLoadout : "{62306181A86F2553}Configs/Loadouts/USAF/USMC/MEF/Loadout_USAF_Base.conf" {
 m_sLoadoutName "#AR-Role_AutomaticRifleman"
 m_sLoadoutResource "{6D23CAB3502EBF3E}Prefabs/Characters/Factions/BLUFOR/RHS_USAF/RHS_USAF_USMC_MEF/Character_Podval_RHS_USAF_USMC_AR.et"
 m_sLoadoutImage "{4FB6C503AD0D21C6}UI/Textures/EditorPreviews/Characters/Factions/BLUFOR/RHS_USAF/RHS_USAF_USMC_MEF/Character_RHS_USAF_USMC_AR.edds"
}