SCR_MissionHeader : "{3F2E005F43DBD2F8}Missions/CAH_Briars_Coast.conf" {
 World "{5A3A20E7719CBDDC}worlds/Podval/Eden/CaptureAndHold/RHS_Inf/Briars_Coast.ent"
 m_sName "Capture & Hold - Briars Coast RHS Infantry"
 m_sAuthor "Podval & Vlad333000"
 m_sDescription "Following the Russian air strike on Morton, a U.S. fuel depot southeast of Manatee was left undefended. Its capture could disrupt plans to evacuate U.S. Army forces from the island."
}