SCR_MissionHeader : "{F1A1BEA67132113E}Missions/CAH_Castle.conf" {
 World "{A0DF4B9E65B8AED5}worlds/Podval/Eden/CaptureAndHold/RHS_Inf/Castle.ent"
 m_sName "Capture & Hold - Montfort Castle RHS Infantry"
 m_sAuthor "Podval & Vlad333000"
 m_sDescription "A small number of US troops are fighting for their lives. Cut off by the Russian forces at Pennants Pass and retreating from Saint-Pierre, they now have no choice but to secure the Montfort Castle. From this ancient stronghold they may be able to hold out, but just a little longer..."
}