SCR_MissionHeader : "{589945FB9FA7B97D}Missions/CAH_Concrete_Plant.conf" {
 World "{1716E4955D229B6D}worlds/Podval/Eden/CaptureAndHold/RHS_Inf/Concrete_Plant.ent"
 m_sName "Capture & Hold - Concrete Plant RHS Infantry"
 m_sAuthor "Podval & Vlad333000"
 m_sDescription "The Arma-Beton concrete plant is a key defensive position on the road to Everon International. If Russian forces take it, they can stage an attack on the airport and surround US troops in Saint-Philippe!"
}