SCR_FactionPlayerLoadout : "{A2D868A81C16FF69}Configs/Loadouts/AFRF/MSV/VKPO_S/Loadout_AFRF_Base.conf" {
 m_sLoadoutName "#AR-Role_AntiTank"
 m_sLoadoutResource "{E474D9098766801A}Prefabs/Characters/Factions/OPFOR/RHS_AFRF/MSV/VKPO_Summer/Character_Podval_RHS_RF_MSV_VKPO_S_AT.et"
}