SCR_FactionPlayerLoadout : "{A2D868A81C16FF69}Configs/Loadouts/AFRF/MSV/VKPO_S/Loadout_AFRF_Base.conf" {
 m_sLoadoutName "#AR-Role_Grenadier"
 m_sLoadoutResource "{F66657CD553CEC8D}Prefabs/Characters/Factions/OPFOR/RHS_AFRF/MSV/VKPO_Summer/Character_RHS_RF_MSV_VKPO_S_GL.et"
 m_sLoadoutImage "{7BF2B1F120295CA3}UI/Textures/EditorPreviews/Characters/Factions/OPFOR/RHS_AFRF/MSV/VKPO_Summer/Character_RHS_RF_MSV_VKPO_S_GL.edds"
}