SCR_FactionPlayerLoadout : "{A2D868A81C16FF69}Configs/Loadouts/AFRF/MSV/VKPO_S/Loadout_AFRF_Base.conf" {
 m_sLoadoutName "#AR-Role_Sharpshooter"
 m_sLoadoutResource "{C55F0D12342C6756}Prefabs/Characters/Factions/OPFOR/RHS_AFRF/MSV/VKPO_Summer/Character_RHS_RF_MSV_VKPO_S_Sharpshooter.et"
 m_sLoadoutImage "{103A91EFE54E6FC8}UI/Textures/EditorPreviews/Characters/Factions/OPFOR/RHS_AFRF/MSV/VKPO_Summer/Character_RHS_RF_MSV_VKPO_S_Sharpshooter.edds"
}