SCR_MissionHeader {
 World "{46B1AAAEC20215CB}worlds/Podval/Eden/CaptureAndHold/RHS/Briars_Coast.ent"
 SystemsConfig "{0E320C55D952E01E}Configs/Systems/CaptureAndHoldSystems.conf"
 m_sName "Capture & Hold - Briars Coast RHS"
 m_sAuthor "Podval & Vlad333000"
 m_sDescription "Following the Russian air strike on Morton, a U.S. fuel depot southeast of Manatee was left undefended. Its capture could disrupt plans to evacuate U.S. Army forces from the island."
 m_sIcon "{B8F3D271E7B1272E}UI/Textures/MissionThumbnails/CAH_BriarsCoast_Thumbnail_UI.edds"
 m_sLoadingScreen "{2771A4843EF492BF}UI/Textures/MissionLoadingScreens/CAH_BriarsCoast_UI.edds"
 m_sPreviewImage "{B8F3D271E7B1272E}UI/Textures/MissionThumbnails/CAH_BriarsCoast_Thumbnail_UI.edds"
 m_sGameMode "Capture & Hold"
 m_iPlayerCount 64
}