SCR_MissionHeader : "{7C491B1FCC0FF0E1}Missions/CAH_LeMoule.conf" {
 World "{CA2C09634ABED9D1}worlds/Podval/Eden/CaptureAndHold/RHS/LeMoule.ent"
 m_sName "Capture & Hold - Le Moule RHS"
 m_sAuthor "Podval & Vlad333000"
 m_sDescription "Russian forces have taken Lamentin. However, NATO forces based at Montignac have responded swiftly, ambushing Russian armor at Le Moule. They must now drive a wedge between this village and the beachhead at Morton, if they wish to hold the island!"
}