SCR_MissionHeader {
 World "{D197678C0D926A07}worlds/Podval/Arland/CaptureAndHold/RHS/Beauregard.ent"
 SystemsConfig "{0E320C55D952E01E}Configs/Systems/CaptureAndHoldSystems.conf"
 m_sName "Capture & Hold - Beauregard RHS"
 m_sAuthor "Podval & Vlad333000"
 m_sDescription "Following the sudden escalation of the conflict on Arland Island, the strategic town of Beauregard found itself on the front line. Control of its intersections, storage areas, and port infrastructure will allow one side to gain a foothold in the region and secure supplies for its forces. Russian Forces and US Army units are striving to take key positions in the town and hold them at all costs."
 m_sIcon "{E44059AE761C1A7D}UI/Textures/MissionThumbnails/GM_Arland.edds"
 m_sLoadingScreen "{94BD54887EAB8288}UI/Textures/MissionLoadingScreens/GM_Arland.edds"
 m_sPreviewImage "{E44059AE761C1A7D}UI/Textures/MissionThumbnails/GM_Arland.edds"
 m_sGameMode "Capture & Hold"
 m_iPlayerCount 64
}