SCR_FactionPlayerLoadout : "{A2D868A81C16FF69}Configs/Loadouts/AFRF/MSV/VKPO_S/Loadout_AFRF_Base.conf" {
 m_sLoadoutName "#AR-Role_Rifleman"
 m_sLoadoutResource "{A0CAC00219D7EF55}Prefabs/Characters/Factions/OPFOR/RHS_AFRF/MSV/VKPO_Summer/Character_RHS_RF_MSV_VKPO_S_Rifleman.et"
 m_sLoadoutImage "{B3CBDB96C5D08BD3}UI/Textures/EditorPreviews/Characters/Factions/OPFOR/RHS_AFRF/MSV/VKPO_Summer/Character_RHS_RF_MSV_VKPO_S_Rifleman.edds"
}