SCR_FactionPlayerLoadout : "{A2D868A81C16FF69}Configs/Loadouts/AFRF/MSV/VKPO_S/Loadout_AFRF_Base.conf" {
 m_sLoadoutName "#AR-Role_AutomaticRifleman"
 m_sLoadoutResource "{FBB329ECA28B85A7}Prefabs/Characters/Factions/OPFOR/RHS_AFRF/MSV/VKPO_Summer/Character_RHS_RF_MSV_VKPO_S_AR.et"
 m_sLoadoutImage "{A1C8CA279CABBAED}UI/Textures/EditorPreviews/Characters/Factions/OPFOR/RHS_AFRF/MSV/VKPO_Summer/Character_RHS_RF_MSV_VKPO_S_AR.edds"
}