SCR_FactionPlayerLoadout : "{62306181A86F2553}Configs/Loadouts/USAF/USMC/MEF/Loadout_USAF_Base.conf" {
 m_sLoadoutName "#AR-Role_LightAT"
 m_sLoadoutResource "{7A2CD5C07BBF7FD5}Prefabs/Characters/Factions/BLUFOR/RHS_USAF/RHS_USAF_USMC_MEF/Character_Podval_RHS_USAF_USMC_LAT.et"
 m_sLoadoutImage "{A04FB52A0DD6A846}UI/Textures/EditorPreviews/Characters/Factions/BLUFOR/RHS_USAF/RHS_USAF_USMC_MEF/Character_RHS_USAF_USMC_LAT.edds"
}