SCR_FactionPlayerLoadout : "{62306181A86F2553}Configs/Loadouts/USAF/USMC/MEF/Loadout_USAF_Base.conf" {
 m_sLoadoutName "#AR-Role_MachineGunner"
 m_sLoadoutResource "{3F3414A93E61ABDD}Prefabs/Characters/Factions/BLUFOR/RHS_USAF/RHS_USAF_USMC_MEF/Character_Podval_RHS_USAF_USMC_MG.et"
 m_sLoadoutImage "{DADB0E8280F7945F}UI/Textures/EditorPreviews/Characters/Factions/BLUFOR/RHS_USAF/RHS_USAF_USMC_MEF/Character_RHS_USAF_USMC_MG.edds"
}