SCR_FactionPlayerLoadout : "{62306181A86F2553}Configs/Loadouts/USAF/USMC/MEF/Loadout_USAF_Base.conf" {
 m_sLoadoutName "#AR-Role_Grenadier"
 m_sLoadoutResource "{60F6B492A799D614}Prefabs/Characters/Factions/BLUFOR/RHS_USAF/RHS_USAF_USMC_MEF/Character_Podval_RHS_USAF_USMC_GL.et"
 m_sLoadoutImage "{958CBED5118FC788}UI/Textures/EditorPreviews/Characters/Factions/BLUFOR/RHS_USAF/RHS_USAF_USMC_MEF/Character_RHS_USAF_USMC_GL.edds"
}