SCR_MissionHeader : "{1CD06B409C6FAE56}Missions/CAH_Forest.conf" {
 m_sName "Capture & Hold - Simon's Wood RHS Infantry"
 m_sAuthor "Podval & Vlad333000"
 m_sDescription "he farm at Simon's Wood sits near the junction of key roads connecting Everon's North, South, and West. A breakthrough here may open up half the island..."
}