SCR_MissionHeader : "{2B4183DF23E88249}Missions/CAH_Morton.conf" {
 World "{AE8D37F53EE42D49}worlds/Podval/CaptureAndHold/Eden/CAH_Eden_Morton_RHS_Inf.ent"
 m_sName "Capture & Hold - Morton RHS Infantry"
 m_sAuthor "Podval & Vlad333000"
 m_sDescription "A small detachment of Russian forces from Kolgujev has established a beachhead at Morton. It may be a feint or the thin end of a wedge, but NATO troops are responding to the threat in force."
}