SCR_MissionHeader : "{9405201CBD22A30C}Missions/CAH_Factory.conf" {
 m_sName "Capture & Hold - Almara Factory RHS Infantry"
 m_sAuthor "Podval & Vlad333000"
 m_sDescription "Saint-Philippe hangs in the balance. Fierce fighting around the furniture factory on the outskirts of the town has forced both sides from the site. But such an impasse cannot last — whoever captures and reinforces this position will most likely take the capital, and Everon itself."
}