SCR_MissionHeader : "{6EA2E454519E5869}Missions/CAH_Military_Base.conf" {
 World "{263FA3B01A4F6B3B}worlds/Podval/CaptureAndHold/Eden/CAH_Eden_Military_Base_RHS_Inf.ent"
 m_sName "Capture & Hold - Camp Blake RHS Infantry"
 m_sAuthor "Podval & Vlad333000"
 m_sDescription "Camp Blake, just south of the village of Levie, overlooks the main road from Saint-Pierre. Additionally, it's situated on a natural chokepoint, where the island narrows. A victory here will cut Everon in half."
}